// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffxljigkoynhrfmxumzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmeGxqaWdrb3luaHJmbXh1bXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjc2ODAsImV4cCI6MjA1ODg0MzY4MH0.8Xx52lhoYRdvPmIH6Uo6d4qzmo7g6YrIo2dvF3uZOxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);